apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: velero-application-set
  namespace: argocd
spec:
  generators:
  - clusters:
      values:
        addon: velero
        namespace: velero
      selector:
        matchLabels:
          addons/velero: "true"
  template:
    metadata:
      name: 'velero-application'
    spec:
      project: multi-cluster-project
      source:
        helm:
          releaseName: '{{.values.addon}}'
          ignoreMissingValueFiles: true
          ValueFiles:
            - values.yaml
            - ../../Clusters/{{.metadata.annotations.env}}/{{.metadata.annotations.aws_cluster_name}}/addons/{{.values.addon}}/values.yaml
          repoURL: {{.metadata.annotations.addons_git_repo}}
        path: HelmCharts/{{.values.addon}}
        targetRevision: '{{.metadata.annotations.addons_git_repo_version}}'
      destination:
        server: '{{server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
