apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: velero-application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: velero
                namespace: velero
              selector:
                  matchExpressions:
                    - key: addons/velero
                      operator: In
                      values: ["true"]
          - clusters: {}
  template:
    metadata:
      name: '{{.values.addonChart}}-{{.name}}'
    spec:
      project: '{{ .metadata.annotations.argocd_project_name }}'
      #project: multi-cluster-hub-spoke-project
      source:
        helm:
          releaseName: '{{.values.addonChart }}'
          ignoreMissingValueFiles: true
          valueFiles:
              - values.yaml
              - '../environments/common/addons{{.values.addonChart}}/values.yaml'
              - '../environments/{{.metadata.annotations.env}}/addons/{{.values.addonChart }}/values.yaml'
              - '../clusters/{{.metadata.annotations.env}}/{{ .metadata.annotations.aws_cluster_name }}/addons/{{.values.addonChart }}/values.yaml'
        repoURL: '{{ .metadata.annotations.addons_git_repo_url }}'
        path: 'HelmCharts/{{.values.addonChart}}'
        targetRevision: '{{ .metadata.annotations.addons_git_repo_version }}'
      destination:
        namespace: '{{ .values.namespace }}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        # managedNamespaceMetadata:
        #   labels:
        #     k8s.twr.io/imageswap: enabled
